# Generated by Django 3.2.9 on 2022-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_image_field_add_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cinema_images/', verbose_name='تصویر'),
        ),
    ]
